export const businessTypes = {
  Trucking: {
    income: ["Freight Income", "Lease Income", "Fuel Surcharge Revenue"],
    expenses: [
      "Fuel Expense",
      "Truck Repairs and Maintenance",
      "Driver Salaries/Wages",
      "Insurance Premiums",
      "Toll Charges",
      "Loan Payment",
      "Accounts Payable",
    ],
    payables: [
      "Provider Payments (Expense) / Money Owed to Suppliers (Expense)",
      "Freight Costs (Expense)",
      "Wages (Expense)",
      "Utilities (Expense)",
      "Taxes (Expense)",
      "Rent (Expense)",
      "Insurance (Expense)",
    ],
  },
  "RIDESHARE DRIVERS/PARTNERS": {
    income: [
      "Fare from Passengers",
      "Bonuses and Incentives",
      "Uber Eats or Lyft Delivery",
    ],
    expenses: [
      "Vehicle Maintenance & Repairs",
      "Fuel",
      "Car Insurance",
      "Vehicle Depreciation",
      "Rideshare Fees",
      "Taxes",
      "Loan Payments (if applicable)",
      "Miscellaneous",
    ],
    payables: [
      "Provider Payments (Expense) / Money Owed to Suppliers (Expense)",
      "Fuel Costs (Expense)",
      "Vehicle Maintenance (Expense)",
      "Insurance (Expense)",
      "Taxes (Expense)",
      "Rent (Expense)",
      "Miscellaneous (Expense)",
    ],
  },
  "Individual/Households": {
    income: [
      "Salary/Wages",
      "Bonuses/Commissions",
      "Self-Employment/Side Hustles",
      "Investment Income",
      "Rental Income",
      "Government Assistance",
      "Pension or Retirement Funds",
      "Alimony/Child Support",
      "Other Income",
    ],
    expenses: [
      "Housing",
      "Transportation",
      "Food & Groceries",
      "Healthcare",
      "Debt Payments",
      "Savings & Investments",
      "Entertainment & Leisure",
      "Childcare & Education",
      "Insurance",
      "Taxes",
      "Miscellaneous",
    ],
    payables: [
      "Bills (Expense)",
      "Rent (Expense)",
      "Utilities (Expense)",
      "Insurance (Expense)",
      "Taxes (Expense)",
      "Debt Payments (Expense)",
      "Miscellaneous (Expense)",
    ],
  },
  Groceries: {
    income: ["Gross Sales", "Delivery Fees", "Rental Income", "Service Fees"],
    expenses: [
      "Cost of Goods Sold (COGS)",
      "Labor Costs",
      "Rent/Lease",
      "Utilities",
      "Insurance",
      "Marketing and Advertising",
      "Supplies",
      "Maintenance and Repairs",
      "Licensing and Permits",
      "Shipping and Delivery",
      "Depreciation",
      "Bank Fees and Interest",
      "Professional Services",
      "Miscellaneous Expenses",
    ],
    payables: [
      "Provider Payments (Expense) / Money Owed to Suppliers (Expense)",
      "Inventory Purchases (Expense)",
      "Inventory Adjustments (Expense)",
      "Utilities (Expense)",
      "Insurance (Expense)",
      "Rent (Expense)",
      "Miscellaneous (Expense)",
    ],
  },
  Cafe: {
    income: [
      "Food Sales",
      "Beverage Sales",
      "Dessert Sales",
      "Takeout or Delivery Sales",
      "Catering or Event Revenue",
      "Gift Cards or Vouchers",
      "Other Income",
    ],
    expenses: [
      "Food Costs",
      "Beverage Costs",
      "Packaging",
      "Supplies for Preparing Food",
      "Labor Costs",
      "Rent or Lease",
      "Utilities",
      "Insurance",
      "Marketing and Advertising",
      "Cleaning and Maintenance",
      "Licenses and Permits",
      "Professional Fees",
      "Equipment and Supplies",
      "Credit Card Fees",
      "Delivery Costs",
      "Depreciation",
      "Interest",
      "Bad Debt",
      "Bank Fees",
      "Miscellaneous",
    ],
    payables: [
      "Provider Payments (Expense) / Money Owed to Suppliers (Expense)",
      "Food Costs (Expense)",
      "Beverage Costs (Expense)",
      "Rent (Expense)",
      "Utilities (Expense)",
      "Insurance (Expense)",
      "Miscellaneous (Expense)",
    ],
  },
  Other: {
    income: [], // Manual entry
    expenses: [], // Manual entry
    payables: [], // Manual entry
  },
};
