export const currencies = {
  USD: { symbol: "$", name: "US Dollar" },
  EUR: { symbol: "€", name: "Euro" },
  GBP: { symbol: "£", name: "British Pound" },
  JPY: { symbol: "¥", name: "Japanese Yen" },
  CNY: { symbol: "¥", name: "Chinese Yuan" },
  INR: { symbol: "₹", name: "Indian Rupee" },
  AUD: { symbol: "A$", name: "Australian Dollar" },
  CAD: { symbol: "C$", name: "Canadian Dollar" },
  CHF: { symbol: "CHF", name: "Swiss Franc" },
  KRW: { symbol: "₩", name: "South Korean Won" },
  PKR: { symbol: "₨", name: "Pakistani Rupee" },
  RUB: { symbol: "₽", name: "Russian Ruble" },
  BRL: { symbol: "R$", name: "Brazilian Real" },
  ZAR: { symbol: "R", name: "South African Rand" },
  MXN: { symbol: "$", name: "Mexican Peso" },
  SEK: { symbol: "kr", name: "Swedish Krona" },
  NOK: { symbol: "kr", name: "Norwegian Krone" },
  DKK: { symbol: "kr", name: "Danish Krone" },
  SGD: { symbol: "S$", name: "Singapore Dollar" },
  HKD: { symbol: "HK$", name: "Hong Kong Dollar" },
  TRY: { symbol: "₺", name: "Turkish Lira" },
  AED: { symbol: "د.إ", name: "United Arab Emirates Dirham" },
  SAR: { symbol: "﷼", name: "Saudi Riyal" },
  IDR: { symbol: "Rp", name: "Indonesian Rupiah" },
  MYR: { symbol: "RM", name: "Malaysian Ringgit" },
  THB: { symbol: "฿", name: "Thai Baht" },
  NZD: { symbol: "NZ$", name: "New Zealand Dollar" },
};
